Vagrant.configure("2") do |config|
  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
  BASE_IP = "192.168.56."

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  # ----------------------------------------------------------
  # Fedora Gateway
  # ----------------------------------------------------------
  config.vm.define "fedora_gateway" do |node|
    node.vm.box = "fedora/41-cloud-base"
    node.vm.hostname = "fedora-gateway.local"
    node.vm.network "public_network", auto_config: true
    node.vm.network "private_network", ip: "#{BASE_IP}10"

    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/playbook.yml"
      ansible.inventory_path = "ansible/hosts.yml"
      ansible.become = true
      ansible.limit = "gateway"
    end
  end

  # ----------------------------------------------------------
  # Fedora Server
  # ----------------------------------------------------------
  config.vm.define "fedora_server" do |node|
    node.vm.box = "fedora/41-cloud-base"
    node.vm.hostname = "fedora-server.local"
    node.vm.network "private_network", ip: "#{BASE_IP}11"

    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/playbook.yml"
      ansible.inventory_path = "ansible/hosts.yml"
      ansible.become = true
      ansible.limit = "fedora_servers"
    end
  end

  # ----------------------------------------------------------
  # Fedora Desktop
  # ----------------------------------------------------------
  config.vm.define "fedora_desktop" do |node|
    node.vm.box = "fedora/41-cloud-base"
    node.vm.hostname = "fedora-desktop.local"
    node.vm.network "private_network", ip: "#{BASE_IP}12"

    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/playbook.yml"
      ansible.inventory_path = "ansible/hosts.yml"
      ansible.become = true
      ansible.limit = "fedora_desktops"
    end
  end

  # ----------------------------------------------------------
  # Kali
  # ----------------------------------------------------------
  config.vm.define "kali" do |node|
    node.vm.box = "kalilinux/rolling"
    node.vm.hostname = "kali.local"
    node.vm.network "private_network", ip: "#{BASE_IP}13"

    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/playbook.yml"
      ansible.inventory_path = "ansible/hosts.yml"
      ansible.become = true
      ansible.limit = "kali_machines"
    end
  end
end
