Vagrant.configure("2") do |config|
  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

  BASE_IP = "192.168.56."

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  # Fedora Server
  config.vm.define "fedora_server" do |node|
    node.vm.box = "fedora/41-cloud-base"
    node.vm.hostname = "fedora-server.local"
    node.vm.network "private_network", ip: "#{BASE_IP}11"
  end

  # Fedora Desktop
  config.vm.define "fedora_desktop" do |node|
    node.vm.box = "fedora/41-cloud-base"
    node.vm.hostname = "fedora-desktop.local"
    node.vm.network "private_network", ip: "#{BASE_IP}12"
  end

  # Kali
  config.vm.define "kali" do |node|
    node.vm.box = "kalilinux/rolling"
    node.vm.hostname = "kali.local"
    node.vm.network "private_network", ip: "#{BASE_IP}13"
  end

  # Ansible provisionamento
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    ansible.inventory_path = "ansible/hosts.yml"
    ansible.become = true
    ansible.limit = "all"
  end
end
