all:
  children:
    fedora_servers:
      hosts:
        fedora_server:
          ansible_host: 192.168.56.11
    fedora_desktops:
      hosts:
        fedora_desktop:
          ansible_host: 192.168.56.12
    kali_machines:
      hosts:
        kali:
          ansible_host: 192.168.56.13
