- name: Configurar Fedora Servers
  hosts: fedora_servers
  become: true
  tasks:
    - name: Atualizar Fedora
      dnf:
        name: "*"
        state: latest

    - name: Criar utilizador "auser"
      user:
        name: auser
        password: "{{ 'horseCACAnow' | password_hash('sha512') }}"
        shell: /bin/bash
        state: present

    - name: Adicionar auser ao grupo wheel
      user:
        name: auser
        groups: wheel
        append: yes

- name: Configurar Fedora Desktops
  hosts: fedora_desktops
  become: true
  tasks:
    - name: Atualizar Fedora
      dnf:
        name: "*"
        state: latest

    - name: Criar utilizador "auser"
      user:
        name: auser
        password: "{{ 'horseCACAnow' | password_hash('sha512') }}"
        shell: /bin/bash
        state: present

    - name: Adicionar auser ao grupo wheel
      user:
        name: auser
        groups: wheel
        append: yes

- name: Configurar Kali
  hosts: kali_machines
  become: true
  tasks:
    - name: Atualizar Kali
      apt:
        update_cache: yes
        upgrade: dist

    - name: Criar utilizador "auser"
      user:
        name: auser
        password: "{{ 'horseCACAnow' | password_hash('sha512') }}"
        shell: /bin/bash
        state: present

    - name: Adicionar auser ao grupo sudo
      user:
        name: auser
        groups: sudo
        append: yes
