---
- name: Configurar Fedora Server
  hosts: fedora_server
  become: true
  tasks:
    - name: Atualizar pacotes do Fedora Server
      dnf:
        name: "*"
        state: latest

    - name: Criar utilizador "auser"
      user:
        name: auser
        password: "{{ 'horseCACAnow' | password_hash('sha512') }}"
        shell: /bin/bash
        state: present

    - name: Adicionar auser ao grupo wheel
      user:
        name: auser
        groups: wheel
        append: yes

- name: Configurar Fedora Desktop
  hosts: fedora_desktop
  become: true
  tasks:
    - name: Atualizar pacotes do Fedora Desktop
      dnf:
        name: "*"
        state: latest

    - name: Criar utilizador "auser"
      user:
        name: auser
        password: "{{ 'horseCACAnow' | password_hash('sha512') }}"
        shell: /bin/bash
        state: present

    - name: Adicionar auser ao grupo wheel
      user:
        name: auser
        groups: wheel
        append: yes

- name: Configurar Kali
  hosts: kali
  become: true
  tasks:
    - name: Atualizar pacotes do Kali
      apt:
        update_cache: yes
        upgrade: dist

    - name: Criar utilizador "auser"
      user:
        name: auser
        password: "{{ 'horseCACAnow' | password_hash('sha512') }}"
        shell: /bin/bash
        state: present

    - name: Adicionar auser ao grupo sudo
      user:
        name: auser
        groups: sudo
        append: yes
