---
# Bootstrap Fedora (Python/libdnf5) necessário para módulos dnf
- name: Preparar Fedora para Ansible
  hosts: fedora_gateway:fedora_servers:fedora_desktops
  become: true
  tasks:
    - name: Instalar Python 3 e libdnf5 via raw
      raw: dnf install -y python3 python3-libdnf5

# Configuração Fedora Gateway
- name: Configurar Fedora Gateway
  hosts: fedora_gateway
  become: true
  tasks:
    - name: Atualizar Fedora
      dnf:
        name: "*"
        state: latest

    - name: Criar utilizador "auser"
      user:
        name: auser
        password: "horseCACAnow"
        shell: /bin/bash
        groups: wheel
        append: yes
        update_password: always

# Configuração Fedora Servers
- name: Configurar Fedora Servers
  hosts: fedora_servers
  become: true
  tasks:
    - name: Atualizar Fedora
      dnf:
        name: "*"
        state: latest

    - name: Criar utilizador "auser"
      user:
        name: auser
        password: "horseCACAnow"
        shell: /bin/bash
        groups: wheel
        append: yes
        update_password: always

# Configuração Fedora Desktops
- name: Configurar Fedora Desktops
  hosts: fedora_desktops
  become: true
  tasks:
    - name: Atualizar Fedora
      dnf:
        name: "*"
        state: latest

    - name: Criar utilizador "auser"
      user:
        name: auser
        password: "horseCACAnow"
        shell: /bin/bash
        groups: wheel
        append: yes
        update_password: always

# Configuração Kali
- name: Configurar Kali
  hosts: kali_machines
  become: true
  tasks:
    - name: Atualizar Kali
      apt:
        update_cache: yes
        upgrade: dist

    - name: Criar utilizador "auser"
      user:
        name: auser
        password: "horseCACAnow"
        shell: /bin/bash
        groups: sudo
        append: yes
        update_password: always